# Generated by Django 4.1 on 2022-08-20 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField(auto_now_add=True)),
                ('schedule_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
                ('schedules_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedules')),
            ],
            options={
                'unique_together': {('schedule_id', 'schedules_id')},
            },
        ),
    ]
