# Generated by Django 4.1 on 2022-08-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultation',
            old_name='schedule_id',
            new_name='schedule',
        ),
        migrations.RenameField(
            model_name='consultation',
            old_name='schedules_id',
            new_name='schedules',
        ),
    ]
