# Generated by Django 4.1 on 2022-09-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_doctor_alter_schedules_schedule'),
        ('consultation', '0002_rename_schedule_id_consultation_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_schedule', to='schedule.schedule'),
        ),
        migrations.AlterField(
            model_name='consultation',
            name='schedules',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_schedules', to='schedule.schedules'),
        ),
    ]
