# Generated by Django 4.1 on 2022-08-20 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('crm', models.CharField(max_length=10)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('specialty_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Specialty', to='doctor.specialty')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
