# Generated by Django 4.1 on 2022-08-23 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty_id',
            new_name='specialty',
        ),
    ]
