# Generated by Django 4.1 on 2022-09-19 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_alter_doctor_specialty'),
        ('schedule', '0002_rename_doctor_id_schedule_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_doctor', to='doctor.doctor'),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules_schedule', to='schedule.schedule'),
        ),
    ]
