# Generated by Django 4.1 on 2022-09-19 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_alter_schedules_schedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedules',
            old_name='availabe',
            new_name='available',
        ),
    ]
